include: all_lint_rules.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    included_file_warning: ignore

linter:
  rules:
    always_specify_types: false
    always_use_package_imports: false
    avoid_annotating_with_dynamic: false
    avoid_positional_boolean_parameters: false
    diagnostic_describe_all_properties: false
    do_not_use_environment: false
    prefer_asserts_with_message: false
    prefer_double_quotes: false
    prefer_final_parameters: false
    public_member_api_docs: false
    unnecessary_final: false
