name: copan_flutter
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  auto_size_text: ^3.0.0
  cupertino_icons: ^1.0.8
  drift: ^2.15.0
  fl_chart: ^0.64.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  flutter_secure_storage: ^9.2.2
  http: ^1.2.0
  intl: any
  package_info_plus: ^5.0.1
  path: ^1.9.0
  path_provider: ^2.1.3
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.1.0
  sqlite3_flutter_libs: ^0.5.24
  syncfusion_flutter_datepicker: ^26.1.39
  uuid: ^4.4.0

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/

