name: copan_flutter
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

  cupertino_icons: ^1.0.2
  auto_size_text: ^3.0.0
  syncfusion_flutter_datepicker: ^19.4.38
  flutter_riverpod: ^1.0.3
  fl_chart: ^0.50.0
  drift: ^1.5.0
  sqlite3_flutter_libs: ^0.5.5
  path_provider: ^2.0.9
  path: ^1.8.0
  drift_dev: ^1.5.2
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.1.10

flutter:
  uses-material-design: true
  generate: true

