name: copan_flutter
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1

  cupertino_icons: ^1.0.2
  auto_size_text: ^3.0.0
  syncfusion_flutter_datepicker: ^23.1.44
  flutter_riverpod: ^2.1.1
  fl_chart: ^0.64.0
  drift: ^2.7.0
  sqlite3_flutter_libs: ^0.5.5
  path_provider: ^2.0.9
  path: ^1.8.0
  http: ^1.1.0
  uuid: ^4.2.1
  qr_flutter: ^4.1.0
  qr_code_scanner: ^1.0.1
  flutter_secure_storage: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/

